### PR TITLE
change model to abstract model

### PR DESCRIPTION
**Pull request by eternaltot**

### CODE REVIEW

**Comment by prince-tanapong** [comment]
Tot you should move script dir to be inside docker dir

**Comment by surasakp** [comment]
You should code follow flake8 style code

**Comment by surasakp** [comment]
In post list view of admin should can to search with title and author. In category list view of admin should can to search with name

**Comment by surasakp** [comment]
In admin can show list of post and category

**Comment by surasakp** [comment]
In post list view of django admin should can to search with title and author. In post list view of django admin should can to search with name

**Pull request merged**
